version: "3.7"
services:
  redis:
    build: docker/redis
    ports:
      - 6379:6379
    volumes:
      - type: volume
        source: redis
        target: /data
  rails:
    build:
      context: .
      dockerfile: docker/rails/Dockerfile
    command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]
    depends_on:
      - redis
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/1
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./app
        target: /app
        consistency: cached
      - type: volume
        source: bundle
        target: /usr/local/bundle
      - type: volume
        source: node_modules
        target: /app/node_modules
volumes:
  redis:
  bundle:
  node_modules:
